import React, { useEffect, useState } from 'react';
import { ArrowUpRight, FileJson, FileText, LoaderCircle, Sparkles } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Job = { job_id: string; status: string; progress: number; source_url: string };
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api/v1';
function App() {
  const [url, setUrl] = useState(''); const [job, setJob] = useState<Job | null>(null); const [error, setError] = useState('');
  useEffect(() => { if (!job || ['completed', 'failed'].includes(job.status)) return; const timer = window.setInterval(async () => { const response = await fetch(`${API}/jobs/${job.job_id}`); if (response.ok) setJob(await response.json()); }, 900); return () => window.clearInterval(timer); }, [job]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); setJob(null); try { const response = await fetch(`${API}/fetch`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ url }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail?.message || 'Unable to create fetch job'); setJob(data); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create fetch job'); } }
  const done = job?.status === 'completed';
  return <main><nav><div className="brand"><span className="mark"><Sparkles size={17} /></span>FETCHER</div><span className="tag">WEB INTELLIGENCE / 01</span></nav><section className="hero"><div className="eyebrow">CONTENT EXTRACTION STUDIO</div><h1>Turn the open web<br /><em>into useful records.</em></h1><p className="intro">Fetch a page. Keep what matters. Leave the noise behind.</p><form onSubmit={submit}><label htmlFor="url">SOURCE URL</label><div className="input-row"><input id="url" value={url} onChange={event => setUrl(event.target.value)} placeholder="https://example.com/article" type="url" required /><button type="submit">FETCH <ArrowUpRight size={18} /></button></div></form>{error && <p className="error">{error}</p>}</section>{job && <section className="status-panel"><div className="status-head"><div><span className="eyebrow">JOB {job.job_id.slice(0, 8)}</span><h2>{job.status === 'completed' ? 'Ready to read.' : job.status === 'failed' ? 'Fetch could not complete.' : 'Working through the page.'}</h2></div><span className={`status ${job.status}`}>{job.status}</span></div><div className="progress"><span style={{ width: `${job.progress}%` }} /></div><div className="status-meta"><span>{job.progress}% processed</span><span>{job.source_url}</span></div>{done && <div className="downloads"><a href={`${API}/jobs/${job.job_id}/files/json`}><FileJson size={18} /> JSON</a><a href={`${API}/jobs/${job.job_id}/files/docx`}><FileText size={18} /> DOCX</a><a href={`${API}/jobs/${job.job_id}/files/pdf`}><FileText size={18} /> PDF</a></div>}{job.status !== 'completed' && job.status !== 'failed' && <LoaderCircle className="spin" size={20} />}</section>}<footer><span>FETCHER / STRUCTURED WEB DATA</span><span>Respecting accessible content and site boundaries.</span></footer></main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
